@baseURL = https://jsonplaceholder.typicode.com
GET {{baseURL}}/posts/1 HTTP/1.1

###
POST {{baseURL}}/posts HTTP/1.1
Content-Type: : application/json

{
  "title": "test",
  "body": "test content",
  "userId": 1,
}

###
PUT {{baseURL}}/posts/1 HTTP/1.1
Content-Type:  application/json

{
  "title": "test",
  "body": "test content",
  "userId": 1,
}

###
DELETE {{baseURL}}/posts/1 HTTP/1.1